### ISSUE TITLE
Support GitOps for deploying models

### ISSUE THREAD

**Issue by kfleischmann** [rocket9-code/mlflow-deployment-controller#18]
I would like to deploy models using a gitops approach. 

**Describe the solution you'd like**
SeldonDeployments are stored inside a git repository. The MLFlowDeploymentController will find those CRDs and apply the latest MODEL URI.

Workflow
- If a new model is stored in MLFlow, this model is automatically deployed into Staging/Production (based on the MLFlow-setup)

**Comment by raghulkrishna** [comment]
@kay this is fixed here https://github.com/rocket9-code/mlflow-deployment-controller/pull/24
