### ISSUE TITLE
Support for MinIO

### ISSUE THREAD

**Issue by spicoflorin** [rocket9-code/mlflow-deployment-controller#37]
Hello!

Does this controller support the MinIO as storage for MLflow?
If yes, what configurations should be passed in order to work?

Thanks,
 Florin

**Comment by raghulkrishna** [comment]
@spicoflorin  yes it supports minio 
please see the example configmap here https://github.com/rocket9-code/mlflow-deployment-controller/blob/main/tests/mlflow-cm.yaml
